name: Backtest SMA & OCO

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Backtest start date (YYYY-MM-DD)'
        required: true
        default: '2015-01-01'
      end:
        description: 'Backtest end date (YYYY-MM-DD, optional)'
        required: false
        default: ''
      limit:
        description: 'Max tickers to test (to keep runtime reasonable)'
        required: true
        default: '300'
      tp:
        description: 'Take profit rate (e.g., 0.06)'
        required: true
        default: '0.06'
      sl:
        description: 'Stop loss rate (e.g., 0.03)'
        required: true
        default: '0.03'
      hold_max:
        description: 'Max holding days'
        required: true
        default: '40'
      priority:
        description: 'Exit priority when both TP/SL reached'
        required: true
        default: 'GapFair'

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backtest
        env:
          PYTHONUTF8: "1"
        run: |
          if [ -z "${{ github.event.inputs.end }}" ]; then
            python backtest_sma_oco.py               --watch watchlist_module.py               --start "${{ github.event.inputs.start }}"               --limit "${{ github.event.inputs.limit }}"               --tp "${{ github.event.inputs.tp }}"               --sl "${{ github.event.inputs.sl }}"               --hold-max "${{ github.event.inputs.hold_max }}"               --priority "${{ github.event.inputs.priority }}"               --outdir backtest_out
          else
            python backtest_sma_oco.py               --watch watchlist_module.py               --start "${{ github.event.inputs.start }}"               --end "${{ github.event.inputs.end }}"               --limit "${{ github.event.inputs.limit }}"               --tp "${{ github.event.inputs.tp }}"               --sl "${{ github.event.inputs.sl }}"               --hold-max "${{ github.event.inputs.hold_max }}"               --priority "${{ github.event.inputs.priority }}"               --outdir backtest_out
          fi

      - name: Upload artifacts (CSV)
        uses: actions/upload-artifact@v4
        with:
          name: backtest_csv
          path: backtest_out/*.csv
          if-no-files-found: warn